#!/usr/bin/env bash
# FNN Dashboard - Session Snapshot Script
# Usage:
#   ./snapshot.sh           Full snapshot with notes prompt
#   ./snapshot.sh --quick   Quick snapshot, no notes prompt

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$PROJECT_DIR/SESSION_NEXT.md"
DATE=$(date '+%Y-%m-%d %H:%M')
QUICK=false

[[ "${1:-}" == "--quick" ]] && QUICK=true

# ---------- Gather data ----------

# Modified files (last 24h)
RECENT_FILES=$(find "$PROJECT_DIR" -name '*.js' -o -name '*.css' -o -name '*.html' -o -name '*.py' | \
  grep -v node_modules | grep -v '.claude' | \
  xargs stat --format='%Y %n' 2>/dev/null | \
  sort -rn | head -30 | \
  awk -v cutoff="$(date -d '24 hours ago' +%s)" '$1 >= cutoff {print $2}')

# Server status
SERVER_PID=$(pgrep -f "node server/index.js" 2>/dev/null || echo "not running")

# JS file count and sizes
JS_FILES=$(find "$PROJECT_DIR/public/js" -name '*.js' 2>/dev/null | wc -l)
CSS_FILES=$(find "$PROJECT_DIR/public/css" -name '*.css' 2>/dev/null | wc -l)

# Check if DB has data
DB_PATH="$PROJECT_DIR/server/data/fnn.db"
if [[ -f "$DB_PATH" ]] && command -v sqlite3 &>/dev/null; then
  DEVICE_COUNT=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM devices;" 2>/dev/null || echo "?")
  SERVICE_COUNT=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM services;" 2>/dev/null || echo "?")
else
  DEVICE_COUNT="?"
  SERVICE_COUNT="?"
fi

# Git status if available
if git -C "$PROJECT_DIR" rev-parse --git-dir &>/dev/null; then
  GIT_STATUS=$(git -C "$PROJECT_DIR" status --short 2>/dev/null || echo "no git")
  GIT_BRANCH=$(git -C "$PROJECT_DIR" branch --show-current 2>/dev/null || echo "unknown")
  GIT_LOG=$(git -C "$PROJECT_DIR" log --oneline -5 2>/dev/null || echo "no commits")
else
  GIT_STATUS="No git repository"
  GIT_BRANCH="n/a"
  GIT_LOG="n/a"
fi

# Notes
NOTES=""
if [[ "$QUICK" == false ]]; then
  echo "Enter session notes (end with empty line):"
  while IFS= read -r line; do
    [[ -z "$line" ]] && break
    NOTES+="- $line"$'\n'
  done
fi

# ---------- Write snapshot ----------

cat > "$OUTPUT" <<SNAPSHOT
# FNN Dashboard - Session Handoff

## Snapshot: $DATE

## Server Status
- PID: $SERVER_PID
- Binding: 0.0.0.0:3000
- Database: $DEVICE_COUNT devices, $SERVICE_COUNT services

## Project Stats
- JS modules: $JS_FILES files in public/js/
- CSS files: $CSS_FILES files in public/css/
- Git branch: $GIT_BRANCH

## Git Status
\`\`\`
$GIT_STATUS
\`\`\`

## Recent Commits
\`\`\`
$GIT_LOG
\`\`\`

## Files Modified (last 24h)
\`\`\`
$(echo "$RECENT_FILES" | sed "s|$PROJECT_DIR/||g")
\`\`\`

## Architecture Quick Reference
- **Backend**: Node.js/Express, SQLite (server/index.js, server/db.js, server/routes/)
- **Frontend**: Vanilla JS IIFE modules (public/js/), CSS glassmorphism (public/css/)
- **Agent**: Python psutil+requests (agent/fnn_agent.py)
- **Key endpoints**: GET /api/dashboard, /api/archive, /api/vpn, /api/counts; POST /api/agent/report

## Current Visual State
- bg-orbs: glassmorphism spheres with logo.png, floating animations
- bg-lightning: faint white/gold sparks between bg-orbs (canvas z-index 1, behind #app z-index 2)
- Service orbs: two-row counter-scrolling carousel (55s), light sweep, status breathing
- Stat cards: compact (CPU/RAM/Free), status glow (green/yellow/red)
- Archive: single combined multi-line chart (8 files, MM/DD dates)
- VPN: per-client chart cards in grid (Sent + Received)
- Animation toggle: header button, persists to localStorage

## JS Module Load Order
api.js -> theme.js -> orbs.js -> lightning.js -> bg-lightning.js -> stats.js -> charts.js -> legend.js -> app.js

## Session Notes
${NOTES:-No notes provided.}

---
*Generated by snapshot.sh — paste this file at the start of your next Claude session*
SNAPSHOT

echo "Snapshot saved to SESSION_NEXT.md"
echo "  Files modified (24h): $(echo "$RECENT_FILES" | grep -c . || echo 0)"
echo "  Server: $SERVER_PID"
echo "  DB: $DEVICE_COUNT devices"
